export const colleges = [
  {
    rank: 1,
    name: "IIT Madras - Indian Institute of Technology (IITM), Chennai",
    fees: 209550,
    placement: { average: 2148000, highest: 19800000 },
    userReviews: 8.6,
    ranking: { india: 3, world: 131 },
    featured: false,
    location: "Chennai, Tamil Nadu",
    totalReviews: 1200,
    icon: "https://example.com/icons/iit-madras.png",
  },
  {
    rank: 2,
    name: "IIT Delhi - Indian Institute of Technology (IITD), New Delhi",
    fees: 254650,
    placement: { average: 2582000, highest: 20000000 },
    userReviews: 8.7,
    ranking: { india: 1, world: 35 },
    featured: false,
    location: "New Delhi, Delhi",
    totalReviews: 1500,
    icon: "https://example.com/icons/iit-delhi.png",
  },
  {
    rank: 3,
    name: "Parul University, Vadodara",
    fees: 149000,
    placement: { average: 400000, highest: 3000000 },
    userReviews: 8.1,
    ranking: { india: 99, world: 147 },
    featured: true,
    location: "Vadodara, Gujarat",
    totalReviews: 800,
    icon: "https://example.com/icons/parul-university.png",
  },
  {
    rank: 4,
    name: "IIT Bombay - Indian Institute of Technology (IITB), Mumbai",
    fees: 229300,
    placement: { average: 2182000, highest: 36700000 },
    userReviews: 8.8,
    ranking: { india: 2, world: 35 },
    featured: false,
    location: "Mumbai, Maharashtra",
    totalReviews: 1300,
    icon: "https://example.com/icons/iit-bombay.png",
  },
  {
    rank: 5,
    name: "BITS Pilani - Birla Institute of Technology and Science, Pilani",
    fees: 312000,
    placement: { average: 1500000, highest: 24000000 },
    userReviews: 8.5,
    ranking: { india: 7, world: 210 },
    featured: false,
    location: "Pilani, Rajasthan",
    totalReviews: 1000,
    icon: "https://example.com/icons/bits-pilani.png",
  },
  {
    rank: 6,
    name: "VIT Vellore - Vellore Institute of Technology, Vellore",
    fees: 198000,
    placement: { average: 1100000, highest: 4400000 },
    userReviews: 7.9,
    ranking: { india: 15, world: 400 },
    featured: false,
    location: "Vellore, Tamil Nadu",
    totalReviews: 900,
    icon: "https://example.com/icons/vit-vellore.png",
  },
  {
    rank: 7,
    name: "SRM Institute of Science and Technology, Chennai",
    fees: 250000,
    placement: { average: 800000, highest: 2500000 },
    userReviews: 7.5,
    ranking: { india: 18, world: 500 },
    featured: true,
    location: "Chennai, Tamil Nadu",
    totalReviews: 850,
    icon: "https://example.com/icons/srm-chennai.png",
  },
  {
    rank: 8,
    name: "Amity University, Noida",
    fees: 220000,
    placement: { average: 600000, highest: 1800000 },
    userReviews: 7.3,
    ranking: { india: 20, world: 650 },
    featured: false,
    location: "Noida, Uttar Pradesh",
    totalReviews: 750,
    icon: "https://example.com/icons/amity-noida.png",
  },
  {
    rank: 9,
    name: "Manipal Institute of Technology, Manipal",
    fees: 270000,
    placement: { average: 1000000, highest: 3200000 },
    userReviews: 8.0,
    ranking: { india: 10, world: 300 },
    featured: false,
    location: "Manipal, Karnataka",
    totalReviews: 950,
    icon: "https://example.com/icons/manipal-institute.png",
  },
  {
    rank: 10,
    name: "Christ University, Bangalore",
    fees: 195000,
    placement: { average: 550000, highest: 1500000 },
    userReviews: 7.7,
    ranking: { india: 25, world: 700 },
    featured: false,
    location: "Bangalore, Karnataka",
    totalReviews: 700,
    icon: "https://example.com/icons/christ-university.png",
  },
  {
    rank: 11,
    name: "Thapar Institute of Engineering and Technology, Patiala",
    fees: 280000,
    placement: { average: 950000, highest: 2700000 },
    userReviews: 8.2,
    ranking: { india: 8, world: 290 },
    featured: true,
    location: "Patiala, Punjab",
    totalReviews: 850,
    icon: "https://example.com/icons/thapar-patiala.png",
  },
  {
    rank: 12,
    name: "Lovely Professional University, Jalandhar",
    fees: 175000,
    placement: { average: 500000, highest: 1200000 },
    userReviews: 7.4,
    ranking: { india: 30, world: 800 },
    featured: false,
    location: "Jalandhar, Punjab",
    totalReviews: 650,
    icon: "https://example.com/icons/lovely-professional.png",
  },
  {
    rank: 13,
    name: "Anna University, Chennai",
    fees: 85000,
    placement: { average: 700000, highest: 2000000 },
    userReviews: 8.3,
    ranking: { india: 5, world: 250 },
    featured: false,
    location: "Chennai, Tamil Nadu",
    totalReviews: 1100,
    icon: "https://example.com/icons/anna-university.png",
  },
  {
    rank: 14,
    name: "Jamia Millia Islamia, New Delhi",
    fees: 60000,
    placement: { average: 600000, highest: 1800000 },
    userReviews: 8.4,
    ranking: { india: 4, world: 220 },
    featured: false,
    location: "New Delhi, Delhi",
    totalReviews: 950,
    icon: "https://example.com/icons/jamia-millia.png",
  },
  {
    rank: 15,
    name: "National Institute of Technology (NIT), Trichy",
    fees: 140000,
    placement: { average: 900000, highest: 2500000 },
    userReviews: 8.5,
    ranking: { india: 6, world: 275 },
    featured: false,
    location: "Tiruchirappalli, Tamil Nadu",
    totalReviews: 800,
    icon: "https://example.com/icons/nit-trichy.png",
  },
  {
    rank: 16,
    name: "Delhi Technological University (DTU), New Delhi",
    fees: 180000,
    placement: { average: 1300000, highest: 2900000 },
    userReviews: 8.7,
    ranking: { india: 9, world: 275 },
    featured: false,
    location: "New Delhi, Delhi",
    totalReviews: 1050,
    icon: "https://example.com/icons/dtu.png",
  },
  {
    rank: 17,
    name: "Jadavpur University, Kolkata",
    fees: 75000,
    placement: { average: 800000, highest: 2200000 },
    userReviews: 8.6,
    ranking: { india: 12, world: 240 },
    featured: false,
    location: "Kolkata, West Bengal",
    totalReviews: 950,
    icon: "https://example.com/icons/jadavpur-university.png",
  },
  {
    rank: 18,
    name: "National Institute of Technology (NIT), Warangal",
    fees: 145000,
    placement: { average: 950000, highest: 2400000 },
    userReviews: 8.4,
    ranking: { india: 11, world: 265 },
    featured: false,
    location: "Warangal, Telangana",
    totalReviews: 900,
    icon: "https://example.com/icons/nit-warangal.png",
  },
  {
    rank: 19,
    name: "PSG College of Technology, Coimbatore",
    fees: 160000,
    placement: { average: 700000, highest: 2000000 },
    userReviews: 8.3,
    ranking: { india: 14, world: 300 },
    featured: true,
    location: "Coimbatore, Tamil Nadu",
    totalReviews: 850,
    icon: "https://example.com/icons/psg-college.png",
  },
  {
    rank: 20,
    name: "BMS College of Engineering, Bangalore",
    fees: 200000,
    placement: { average: 600000, highest: 1700000 },
    userReviews: 8.1,
    ranking: { india: 22, world: 350 },
    featured: false,
    location: "Bangalore, Karnataka",
    totalReviews: 750,
    icon: "https://example.com/icons/bms-college.png",
  },
  {
    rank: 21,
    name: "RV College of Engineering, Bangalore",
    fees: 210000,
    placement: { average: 750000, highest: 2200000 },
    userReviews: 8.2,
    ranking: { india: 19, world: 310 },
    featured: false,
    location: "Bangalore, Karnataka",
    totalReviews: 800,
    icon: "https://example.com/icons/rv-college.png",
  },
  {
    rank: 22,
    name: "National Institute of Technology (NIT), Surathkal",
    fees: 150000,
    placement: { average: 1000000, highest: 2500000 },
    userReviews: 8.5,
    ranking: { india: 16, world: 280 },
    featured: false,
    location: "Surathkal, Karnataka",
    totalReviews: 850,
    icon: "https://example.com/icons/nit-surathkal.png",
  },
  {
    rank: 23,
    name: "National Institute of Technology (NIT), Rourkela",
    fees: 135000,
    placement: { average: 850000, highest: 2300000 },
    userReviews: 8.3,
    ranking: { india: 17, world: 290 },
    featured: false,
    location: "Rourkela, Odisha",
    totalReviews: 820,
    icon: "https://example.com/icons/nit-rourkela.png",
  },
  {
    rank: 24,
    name: "IIIT Hyderabad - International Institute of Information Technology, Hyderabad",
    fees: 280000,
    placement: { average: 1800000, highest: 3500000 },
    userReviews: 8.9,
    ranking: { india: 13, world: 220 },
    featured: false,
    location: "Hyderabad, Telangana",
    totalReviews: 950,
    icon: "https://example.com/icons/iiit-hyderabad.png",
  },
  {
    rank: 25,
    name: "VJTI Mumbai - Veermata Jijabai Technological Institute, Mumbai",
    fees: 130000,
    placement: { average: 950000, highest: 2100000 },
    userReviews: 8.0,
    ranking: { india: 21, world: 320 },
    featured: false,
    location: "Mumbai, Maharashtra",
    totalReviews: 780,
    icon: "https://example.com/icons/vjti-mumbai.png",
  },
  {
    rank: 26,
    name: "University of Hyderabad, Hyderabad",
    fees: 95000,
    placement: { average: 750000, highest: 1800000 },
    userReviews: 8.1,
    ranking: { india: 23, world: 340 },
    featured: false,
    location: "Hyderabad, Telangana",
    totalReviews: 750,
    icon: "https://example.com/icons/university-of-hyderabad.png",
  },
  {
    rank: 27,
    name: "Aligarh Muslim University (AMU), Aligarh",
    fees: 55000,
    placement: { average: 500000, highest: 1600000 },
    userReviews: 7.8,
    ranking: { india: 24, world: 360 },
    featured: false,
    location: "Aligarh, Uttar Pradesh",
    totalReviews: 700,
    icon: "https://example.com/icons/amu.png",
  },
  {
    rank: 28,
    name: "Punjab Engineering College (PEC), Chandigarh",
    fees: 170000,
    placement: { average: 700000, highest: 1900000 },
    userReviews: 7.9,
    ranking: { india: 26, world: 380 },
    featured: true,
    location: "Chandigarh, Punjab",
    totalReviews: 730,
    icon: "https://example.com/icons/pec-chandigarh.png",
  },
  {
    rank: 29,
    name: "College of Engineering, Pune (COEP)",
    fees: 140000,
    placement: { average: 800000, highest: 2100000 },
    userReviews: 8.2,
    ranking: { india: 27, world: 400 },
    featured: false,
    location: "Pune, Maharashtra",
    totalReviews: 780,
    icon: "https://example.com/icons/coep-pune.png",
  },
  {
    rank: 30,
    name: "Osmania University, Hyderabad",
    fees: 85000,
    placement: { average: 600000, highest: 1600000 },
    userReviews: 7.6,
    ranking: { india: 28, world: 420 },
    featured: false,
    location: "Hyderabad, Telangana",
    totalReviews: 720,
    icon: "https://example.com/icons/osmania-university.png",
  },
];
